receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  resource:
    attributes:
      - key: deployment.environment
        value: "local"
        action: insert
      - key: service.instance.id
        from_attribute: service.name
        action: insert

  # Memory limiter to prevent OOM
  memory_limiter:
    limit_mib: 512
    check_interval: 2s

exporters:
  # Debug exporter for local testing (replaces deprecated logging exporter)
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  # Dynatrace exporter - configure with your Dynatrace details
  otlphttp/dynatrace:
    endpoint: "##############"
    headers:
      Authorization: "Api-Token dt0c01.##################################"
    compression: gzip

  # Alternative OTLP HTTP exporter for other backends
  otlphttp:
    endpoint: "http://localhost:4318"
    compression: gzip

  # OTLP gRPC exporter
  otlp:
    endpoint: "localhost:4317"
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlphttp/dynatrace]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlphttp/dynatrace]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug, otlphttp/dynatrace]

  telemetry:
    logs:
      level: "debug"
    metrics:
      level: detailed
